//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishTranslationQuiz.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnglishTranslationQuiz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Again.
        /// </summary>
        internal static string Quiz_Again {
            get {
                return ResourceManager.GetString("Quiz_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All words learned!.
        /// </summary>
        internal static string Quiz_AllWordsLearned {
            get {
                return ResourceManager.GetString("Quiz_AllWordsLearned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Quiz_Back {
            get {
                return ResourceManager.GetString("Quiz_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know.
        /// </summary>
        internal static string Quiz_IDontKnow {
            get {
                return ResourceManager.GetString("Quiz_IDontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know it.
        /// </summary>
        internal static string Quiz_Know {
            get {
                return ResourceManager.GetString("Quiz_Know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show translation.
        /// </summary>
        internal static string Quiz_ShowTranslation {
            get {
                return ResourceManager.GetString("Quiz_ShowTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Startup_Loading {
            get {
                return ResourceManager.GetString("Startup_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No words found!.
        /// </summary>
        internal static string Startup_NoWordsFound {
            get {
                return ResourceManager.GetString("Startup_NoWordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Open
        ///Directory.
        /// </summary>
        internal static string Startup_OpenDirectory {
            get {
                return ResourceManager.GetString("Startup_OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open
        /// File.
        /// </summary>
        internal static string Startup_OpenFile {
            get {
                return ResourceManager.GetString("Startup_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
